language: ruby

sudo: false
cache: bundler

branches:
  only:
    - master

rvm:
  - 2.2
  - 2.3.0
  - 2.4.0
  - jruby-19mode

gemfile:
  - gemfiles/Gemfile-rspec-3.4.x
  - gemfiles/Gemfile-rspec-3.5.x
